Feat: [SISO-33] typeorm 세팅 및 db 마이그레이션
TeamTuesday/siso-backend pull request #11
Opened 2022-06-15 04:44 UTC by sua-no

# Link

- Jira Issue Ticket: https://teamtuesday.atlassian.net/browse/SISO-33, https://teamtuesday.atlassian.net/browse/SISO-34
- Techspec: https://teamtuesday.atlassian.net/l/c/a9H6t91V

# Summary

- typeorm 세팅 및 db 마이그레이션
(내가 뭘 했는지 : 작업에 대한 설명, 기존코드와 변경점 등)

# ETC

- database 모듈의 위치가 src여야하는지 lib/config여야하는지
- ormconfig.ts에 entities가 path로 불러와지지않아서 직접 entity넣었는데 이 부분은 수정이 필요할 것 같음
(PR에 대한 추가 설명 혹은 작업시 고민되었던 부분)

# Before I request PR review

.env에 디비 정보 추가 DATABASE_USERNAME, DATABASE_PASSWORD
서버 구동시 db에 vote-subject 테이블 생기는지 확인
(내가 PR 리뷰 부탁하기 전에 한 일)

# After this PR reviewed

(PR 리뷰가 끝난다면 뭘 해야 하는가? Merge 전 필요한 Process들)

# Expected due date

(희망 리뷰 완료일, 최소기준 : 배포 3일 전까지)

2022-06-15 13:54 UTC, hoontae24 requested changes
@sua-no `vote-subject` 리소스에 대해서 `entity`가 `module`에 포함될 순 없는 구조인가요?

2022-06-15 13:54 UTC, hoontae24 commented on src/migration/1655265681090-Test.ts
> +    }
@sua-no
- 마이그레이션 코드는 서버 어플리케이션이랑 완전히 분리하는 게 좋을 것 같습니다. src 폴더에 위치할 필요가 있을까요?
- `queryRunner`에 sql말고 함수 인터페이스로도 DDL 작성할 수 있을 것 같은데, 그게 더 관리하기 편하지 않을까요?

2022-06-15 13:54 UTC, hoontae24 commented on src/ormconfig.ts
> +  synchronize: process.env.NODE_ENV === 'production' ? false : true,
@sua-no `env` 값을 대신 처리하는 `ConfigModule`을 이용해서 처리할 수 없는지 체크해주시면 좋을 것 같습니다~!

2022-06-16 15:14 UTC, Jangyusu approved these changes, later dismissed

2022-06-19 03:49 UTC, sua-no commented on src/migration/1655265681090-Test.ts
> +    }
- src폴더에 위치하지 않고 lib/config만드신거처럼 root에 따로 분리하는게 좋을거같다고 하시는걸까요?
- 마이그레이션 파일은 typeorm으로 마이그레이션 시 자동으로 생성되는 파일입니다..!

2022-06-19 03:49 UTC, sua-no commented on src/ormconfig.ts
> +  synchronize: process.env.NODE_ENV === 'production' ? false : true,
네 새로 커밋남기겠습니다 :)

2022-06-19 03:52 UTC, sua-no reviewed
@hoontae24  ormconfig에서 entity 폴더 path를 넣어서 한번에 entity파일을 참조하여 테이블 생성이 되기 때문에 일반적으로 entity파일을 따로 모아두더라구요! 제가 해당 path를 못읽어와서 현재 entity를 따로 불러온상태기 때문에 그걸 적용하지 못했는데 이거는 수정이 추후 되어야할거같습니다

2022-06-19 04:57 UTC, sua-no commented on src/ormconfig.ts
> +  synchronize: process.env.NODE_ENV === 'production' ? false : true,
찾아봤는데 설정파일에서 nest 모듈을 불러와서 사용하기는 어려울것 같습니다 😅

2022-06-19 14:53 UTC, hoontae24 commented on src/migration/1655265681090-Test.ts
> +    }
이건 저도 좀 더 봐야겠네요~!

2022-06-19 14:56 UTC, hoontae24 commented
> @hoontae24 ormconfig에서 entity 폴더 path를 넣어서 한번에 entity파일을 참조하여 테이블 생성이 되기 때문에 일반적으로 entity파일을 따로 모아두더라구요! 제가 해당 path를 못읽어와서 현재 entity를 따로 불러온상태기 때문에 그걸 적용하지 못했는데 이거는 수정이 추후 되어야할거같습니다

typeorm 은 어떤 패턴으로 쓰는지 모르겠네요. 저는 @nestjs/cli로 컴포넌트 생성하면 entity랑 dto가 모듈로 생성되길래 그게 자연스러운 거라고 생각했습니다 ~!

2022-06-19 15:05 UTC, hoontae24 commented on src/ormconfig.ts
> +export = ormConfig;
`export =`는 어떤 의미인가요? `export default`를 쓰지 않는 이유가 있을까요?

2022-06-19 15:08 UTC, hoontae24 commented on src/ormconfig.ts
> +  synchronize: process.env.NODE_ENV === 'production' ? false : true,
직접 해보진 않았지만... 참고 해볼만한 것 같습니다~!
https://gaemi606.tistory.com/entry/NestJS-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%97%B0%EA%B2%B0-%EC%84%A4%EC%A0%95-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EC%9E%85%EB%A0%A5%ED%95%98%EB%8A%94-%EB%8B%A4%EC%96%91%ED%95%9C-%EB%B0%A9%EB%B2%95-database-connection

2022-06-20 01:00 UTC, sua-no commented on src/ormconfig.ts
> +  synchronize: process.env.NODE_ENV === 'production' ? false : true,
네 참고해서 작업해보겠습니다~!

2022-06-20 01:00 UTC, sua-no reviewed
https://github.com/typeorm/typeorm/tree/master/sample/sample1-simple-entity

2022-06-22 09:51 UTC, sua-no reviewed
@hoontae24 @Jangyusu
- entity파일은 모듈안에 위치
- config에 데이터 베이스 모듈 추가
- config module사용하여 env 불러오는것으로 수정하였습니다
마이그레이션 부분 제외하고 작동하는것 확인했습니다

2022-06-23 11:55 UTC, hoontae24 commented
@sua-no database 모듈의 역할은 뭔가요?

2022-06-23 11:58 UTC, hoontae24 commented on src/app.module.ts
> +  providers: [AppService, ConfigService],
@sua-no `app.module.ts` 모듈에 `ConfiService`가 `providers`에 등록되는 이유가 궁금합니다~! `ConfigModule`을 `imports`에 등록하면 동작하는 것 아닌가 해서요~

2022-06-24 08:43 UTC, sua-no commented on src/app.module.ts
> +  providers: [AppService, ConfigService],
네 database모듈에도 providers 등록했네요 둘다 삭제했습니다!

2022-06-24 08:44 UTC, sua-no reviewed
@hoontae24 
typeorm 세팅 및 db에 연결하는 용도로 database 모듈을 따로 만들었습니다
세팅도 모듈화하자고 하셨던거같아서요..!

2022-06-25 04:13 UTC, hoontae24 approved these changes, later dismissed

2022-06-28 12:15 UTC, Jangyusu submitted a review, later dismissed

2022-06-28 12:18 UTC, sua-no commented on src/ormconfig.ts
> +export = ormConfig;
export default 랑 같은 의미인거같습니다 ormconfig삭제해서 우선 닫겠습니다..!

2022-06-29 00:53 UTC, Jangyusu approved these changes

2022-06-29 00:57 UTC, sua-no reviewed
@hoontae24 @Jangyusu 
참고로
- databaseService에 entity 추가
- databaseService에 synchronize:true
- env에 로컬 db접속 정보 추가
하시면 db에 테이블 생성됩니다
테크 스펙에도 적어두겠습니다

2022-06-29 01:41 UTC, hoontae24 approved these changes

2022-06-29 01:50 UTC, merged